version: '3.8'
services:
  backend_dev:
    stdin_open: true
    ports:
      - "3006:3000"
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./backend:/usr/app
    restart: on-failure
  postgres-db:
    image: "postgres"
    restart: "always"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: abc123